=== sonicka/423191-pb029-project/src/main/resources/address-book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="addressbook" type="addressbookType"/>

  <xs:complexType name="nameType">
    <xs:sequence>
      <xs:element name="firstname" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="middlename" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="lastname" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="addressType">
    <xs:sequence>
      <xs:element name="street" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="doornumber" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
      <xs:element name="postalnumber" type="xs:int" minOccurs="1" maxOccurs="1"/>
      <xs:element name="city" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="state" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="contactType">
    <xs:sequence>
      <xs:element name="email" type="emailType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="phonenumber" type="phoneNumberType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="website" type="xs:anyURI" minOccurs="0" maxOccurs="4"/>
      <xs:element name="other" type="otherType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="personType">
    <xs:sequence>
      <xs:element name="name" type="nameType" minOccurs="1" maxOccurs="1"/>
      <xs:element name="contact" type="contactType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="address" type="addressType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="otherType">
    <xs:sequence>
      <xs:element name="nameofservice" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="userid" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="addressbookType">
    <xs:sequence>
      <xs:element name="person" type="personType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="title"/>
  </xs:complexType>

  <xs:simpleType name="emailType">
    <xs:restriction base="xs:token">
      <xs:maxLength value="254"/>
      <xs:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="phoneNumberType">
    <xs:simpleContent>
      <xs:extension base="number">
        <xs:attribute name="type" type="phoneAtt"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="number">
    <xs:restriction base="xs:string">
      <xs:pattern value="\+?\d+"/>
      <xs:minLength value="3"/>
      <xs:maxLength value="15"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="phoneAtt">
      <xs:restriction base="xs:string">
          <xs:enumeration value="personal"/>
          <xs:enumeration value="work"/>
          <xs:enumeration value="other"/>
      </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== sonicka/423191-pb029-project/src/main/resources/valid-real-world-records.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="addressbook-to-html.xsl"?>
<addressbook title="addressbook" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="address-book.xsd">
    <person>
        <name>
            <firstname>Emrick</firstname>
            <lastname>Hamlin</lastname>
        </name>
        <contact>
            <email>emric-haml@yahoo.com</email>
            <phonenumber type="work">+5553004487</phonenumber>
            <website>www.google.com</website>
            <other>
                <nameofservice>Skype</nameofservice>
                <userid>emrickham</userid>
            </other>
        </contact>
        <address>
            <street>Silent Lagoon</street>
            <doornumber>1953</doornumber>
            <postalnumber>677152937</postalnumber>
            <city>New York</city>
            <state>US</state>
        </address>
    </person>

    <person>
        <name>
            <firstname>Malka</firstname>
            <lastname>Plumb</lastname>
        </name>
        <contact>
            <phonenumber>+5553774253</phonenumber>
        </contact>
        <notes>Burrow under covers eats owners hair then claws head, missing until dinner time plays league of legends and kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff give attitude, for rub whiskers on bare skin act innocent. Have secret plans eat and than sleep on your face, yet claws in your leg. Missing until dinner time. Asdflkjaertvlkjasntvkjn (sits on keyboard) man running from cops stops to pet cats, goes to jail. Cats making all the muffins. </notes>
    </person>

    <person>
        <name>
            <firstname>Efrain</firstname>
            <middlename>Harbour</middlename>
            <lastname>Lybarger</lastname>
        </name>
        <contact>
            <email>elflyb@gmail.com</email>
            <phonenumber type="work">8488811</phonenumber>
            <phonenumber type="personal">+5554569874</phonenumber>
            <phonenumber>+5553211479</phonenumber>
            <other>
                <nameofservice>ICQ</nameofservice>
                <userid>632489025</userid>
            </other>
        </contact>
        <address>
            <street>Pleasant Nectar St.</street>
            <doornumber>658</doornumber>
            <postalnumber>327945582</postalnumber>
            <city>Seattle</city>
            <state>United States</state>
        </address>
    </person>

    <person>
        <name>
            <firstname>Shah </firstname>
            <lastname>Watkins</lastname>
        </name>
        <contact>
            <email>shah_wa@toodles.com</email>
            <email>shahahah@gmail.com</email>
            <email>watkinss@yahoo.com</email>
            <website>haha.com</website>
            <website>hehe.com</website>
        </contact>
        <notes>Bulbasaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ivysaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Venusaur Lorem ipsum dolor sit amet, consectetur adipiscing elit. Charmander Lorem ipsum dolor sit amet, consectetur adipiscing elit.</notes>
    </person>

    <person>
        <name>
            <firstname>Reinhard</firstname>
            <middlename>Green</middlename>
            <lastname>Hibbard</lastname>
        </name>
        <contact>
            <phonenumber type="personal">9014669746</phonenumber>
            <other>
                <nameofservice>Skype</nameofservice>
                <userid>hibbi</userid>
            </other>
            <other>
                <nameofservice>ICQ</nameofservice>
                <userid>160258943</userid>
            </other>
        </contact>
        <address>
            <street>Gentle Grounds</street>
            <doornumber>1912</doornumber>
            <postalnumber>654652</postalnumber>
            <city>Highway Village</city>
            <state>Canada</state>
        </address>
        <notes>Northern squawfish skate, cod icefish, bass ricefish; murray cod. Mustache triggerfish combtail gourami queen danio damselfish frilled shark. </notes>
    </person>
</addressbook>

=== sonicka/423191-pb029-project/src/main/resources/address-book.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="addrssbook-to-html.xsl"?>
<addressbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="address-book.xsd">
<person>
    <name>
        <firstname>Sona</firstname>
        <middlename></middlename>
        <lastname>Leitmanova</lastname>
    </name>
    <contact>
        <email>sona.leitmanova@gmail.com</email>
        <phonenumber type="personal">+421908607121</phonenumber>
        <phonenumber>+420607123104</phonenumber>
        <website></website>
        <other>
            <nameofservice>ICQ</nameofservice>
            <userid>301283667</userid>
        </other>
    </contact>
    <address>
        <street>Chodska</street>
        <doornumber>7</doornumber>
        <postalnumber>61200</postalnumber>
        <city>Brno</city>
        <state>Czech Republic</state>
    </address>
    <notes>lalala</notes>
</person>
</addressbook>
